# **Onsite Class 01**

## Implementation 50 methods of numpy 

In [1]:
%pip install numpy nptyping numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
from nptyping import NDArray , Shape, UInt64
import numpy as np

a : np.ndarray = np.array(1000)


display(a)
display(a.shape)
display(a.dtype)
display(type(a))
display(a.ndim)
display(a.size)
display(a.itemsize)

array(1000)

()

dtype('int64')

numpy.ndarray

0

1

8

# **Array creations**

In [70]:
import pandas as pd

table_data : pd.DataFrame = pd.read_excel("./arr_creation.xlsx")

table_data

Method                                        Description  \
0          array()  Create a new NumPy array from a Python list, t...   
1          empty()  Create a new NumPy array of a given shape and ...   
2     empty_like()  Create a new NumPy array with the same shape a...   
3            eye()  Create a new NumPy identity matrix of a given ...   
4       fromfile()       Create a new NumPy array from a binary file.   
5   fromfunction()  Create a new NumPy array from a function that ...   
6       identity()  Create a new NumPy identity matrix of a given ...   
7       linspace()  Create a new NumPy array with evenly spaced el...   
8       logspace()  Create a new NumPy array with evenly spaced el...   
9          mgrid()  Create a new NumPy meshgrid of evenly spaced p...   
10         ogrid()  Create a new NumPy open meshgrid of evenly spa...   
11          ones()  Create a new NumPy array of a given shape and ...   
12     ones_like()  Create a new NumPy array with the same shape a...   
13            r_()  Concatenate two NumPy arrays along the first a...   
14         zeros()  Create a new NumPy array of a given shape and ...   
15    zeros_like()  Create a new NumPy array with the same shape a...   

                                        Example  
0                     np.array([1, 2, 3, 4, 5])  
1                   np.empty((2, 3), dtype=int)  
2                       np.empty_like(my_array)  
3                                     np.eye(3)  
4         np.fromfile("my_file.bin", dtype=int)  
5   np.fromfunction(lambda i, j: i * j, (3, 3))  
6                                np.identity(3)  
7                        np.linspace(0, 10, 10)  
8                        np.logspace(1, 10, 10)  
9                               mgrid[0:3, 0:3]  
10                              ogrid[0:3, 0:3]  
11                   np.ones((2, 3), dtype=int)  
12                       np.ones_like(my_array)  
13                  np.r_[my_array1, my_array2]  
14                  np.zeros((2, 3), dtype=int)  
15                      np.zeros_like(my_array)

#### Method 01 ( arange() )

Create a new NumPy array from a Python list, tuple, or other sequence.

In [5]:
from typing import Any


arr1_list : NDArray[Shape["10"],Any] = np.arange(1,11)

arr1_list

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Method 02 ( array() ) 

Create a new NumPy array from a Python list, tuple, or other sequence.

In [11]:
from typing import Any

d1 : NDArray[Shape["10"], Any] = np.array([1,2,4,5,6,7,8])

d1

array([1, 2, 4, 5, 6, 7, 8])

In [12]:
d1 + 5

array([ 6,  7,  9, 10, 11, 12, 13])

In [15]:
%%time

data : NDArray[Shape["10"],Any] = np.arange(1,100000)

data + 5 # addition operation

CPU times: user 2.41 ms, sys: 532 µs, total: 2.94 ms
Wall time: 1.96 ms


array([     6,      7,      8, ..., 100002, 100003, 100004])

# method 03 ( empty() )

Create a new NumPy array of a given shape and data type, initialized with all zeros.

### syntax

```python
empty(shape, dtype=float, order='C', *, like=None)

```
Return a new array of given shape and type, without initializing entries

In [35]:
from nptyping import NDArray

my_array : NDArray[Shape['10'], Any] = np.empty((2, 3), dtype=int)

my_array

# This will not raise an error
# my_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)


array([[50438108,        0,        0],
       [       0,        0,        0]])

## method 04 **empty_like()**

Create a new `NumPy` array with the same shape and data type as an existing 

NumPy array, initialized with all zeros.

In [38]:
import numpy as np
arr2 : NDArray[Shape["Size"],Any] = np.zeros((2,2))

arr2

array([[0., 0.],
       [0., 0.]])

# M5 **eye**

Create a new NumPy identity matrix of a given size.

**Syntax**

```raw
Parameters
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to N.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
```

In [40]:
arr3 : NDArray[Shape['Size'],Any] = np.eye(3,2) # N=no. of rows M=no. oof colums

arr3

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

## M6 **fromfile()**

Create a new NumPy array from a binary file.

In [45]:
# Create a NumPy array of binary code.
arr4 : NDArray[Shape["Size"],Any] = np.fromfile("abc1.txt",dtype=int)

# printing encoded data in numeric form
print(arr4) 

# decode binary string
decode_string : str = b"".join(arr4).decode()
print(decode_string)



[7953766455951712592 7070758498948708896 8534158704748487777
 8026294636872933477]
Pakistan zinda badWE love our co


## M7 **fromfunction**

Create a new NumPy array from a function that takes an array of 

indices as input and returns an array of values as output.

In [47]:
m7 : NDArray[Shape["Size"],Any] = np.fromfunction(lambda i , j : i * j , (3,6)) # 3 = row , 6 = columns

print(m7)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  5.]
 [ 0.  2.  4.  6.  8. 10.]]


## M8 **Identity**

Create a new NumPy identity matrix of a given size.

In [49]:
m8 : NDArray[Shape['Size'],Any] = np.identity(3) # creates an identity matrics

m8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## M9 **linespace()**

Create a new NumPy array with evenly spaced elements between a given start and end point.

In [50]:
m9 : NDArray[Shape['Size'],Any] = np.linspace(0,10,10) # start , stop , num = number of samples to generate

m9

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

## m10 **logspace()**
Create a new NumPy array with evenly spaced elements on a logarithmic scale 

between a given start and end point.


In [51]:
m10 : NDArray[Shape['Size'],Any] = np.logspace(1,10,10) # start , stop , num = supported index

m10

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

## m11 **mgrid()**

Create a new NumPy meshgrid of evenly spaced points in two or more dimensions.

In [52]:
m11 : NDArray[Shape['Size'],Any] = np.mgrid[0:3, 0:3]

m11

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

## m12 **ogrid**

Create a new NumPy open meshgrid of evenly spaced points in two or more dimensions.

In [60]:
m12 : list[NDArray] = np.ogrid[0:3,0:3]

m12

[array([[0],
        [1],
        [2]]),
 array([[0, 1, 2]])]

## m13 **ones()**

Create a new NumPy array of a given shape and data type, initialized with all ones.

In [62]:
m13 : NDArray[Shape['Size'],Any] = np.ones((2,3), dtype=int) # 2 = rows , 3 = columns

m13

array([[1, 1, 1],
       [1, 1, 1]])

## m14 **ones_like()**

Create a new NumPy array with the same shape and data type as an 

existing NumPy array, initialized with all ones.

In [64]:
m14 : NDArray[Shape['Size'],Any] = np.ones_like([1,2,3,4,5]) # 2 = rows , 3 = columns

m14

array([1, 1, 1, 1, 1])

## m15 **r_()**
Concatenate two `NumPy` arrays along the `first` axis.


In [65]:
m15 : NDArray[Shape['Size'],Any] = np.r_[['a','b','c'],[1,2,3]]

m15

array(['a', 'b', 'c', '1', '2', '3'], dtype='<U21')

## m16 **zeros()**

Create a new NumPy array of a given shape and data type, initialized with all zeros.

In [67]:
m16 : NDArray[Shape['Size'],Any] = np.zeros((2,4),dtype=int)

m16

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

## m17 **zeros_like()**
Create a new NumPy array with the same shape and data type as an 

existing NumPy array, initialized with all zeros.


In [68]:
m17 : NDArray[Shape['Size'],Any] = np.zeros_like([1,2,3,4])

m17

array([0, 0, 0, 0])

# **Array operations**

In [69]:
import pandas as pd

table_data : pd.DataFrame = pd.read_excel("./arr_operations.xlsx")

table_data

Method                                        Description  \
0        add()                              Add two NumPy arrays.   
1   subtract()                         Subtract two NumPy arrays.   
2   multiply()                         Multiply two NumPy arrays.   
3     divide()                           Divide two NumPy arrays.   
4        mod()  Compute the remainder of dividing two NumPy ar...   
5      power()                    Raise a NumPy array to a power.   
6    maximum()  Return the element-wise maximum of two NumPy a...   
7    minimum()  Return the element-wise minimum of two NumPy a...   
8        sum()                 Sum the elements of a NumPy array.   
9       mean()  Compute the mean of the elements of a NumPy ar...   
10    median()  Compute the median of the elements of a NumPy ...   

                              Example  
0        np.add(my_array1, my_array2)  
1   np.subtract(my_array1, my_array2)  
2   np.multiply(my_array1, my_array2)  
3     np.divide(my_array1, my_array2)  
4        np.mod(my_array1, my_array2)  
5               np.power(my_array, 2)  
6    np.maximum(my_array1, my_array2)  
7    np.minimum(my_array1, my_array2)  
8                    np.sum(my_array)  
9                   np.mean(my_array)  
10                np.median(my_array)

## m18 **add()**
 

In [73]:
import numpy as np
from nptyping import NDArray, Shape
from typing import Any, Generic

# Create two NumPy arrays
a : NDArray[Shape['Size'], Any] = np.array([1, 2, 3, 4, 5])
b : NDArray[Shape['Size'], Any] = np.array([6, 7, 8, 9, 10])

# Add the two arrays
c : NDArray[Shape['Size'], Any] = np.add(a, b)

# Print the result
print(c)

# Output: [7 9 11 13 15]


[ 7  9 11 13 15]


## m19 **subtract()**

In [75]:
# Create two NumPy arrays
a : NDArray[Shape['Size'], Any] = np.array([1, 2, 3, 4, 5])
b : NDArray[Shape['Size1','Size2'], Any] = np.array([6, 7, 8, 9, 10])

# Add the two arrays
c : NDArray[Shape['Size'], Any] = np.subtract(b,a)

# Print the result
print(c)

[5 5 5 5 5]


## m20 **multiply()**

In [77]:

print(f"a : {a}")
print(f"b : {b}")
# Add the two arrays
c : NDArray[Shape['Size'], Any] = np.multiply(b,a)

# Print the result
print(c)

a : [1 2 3 4 5]
b : [ 6  7  8  9 10]
[ 6 14 24 36 50]


## m21 **divide()**

In [78]:

print(f"a : {a}")
print(f"b : {b}")
# Add the two arrays
c : NDArray[Shape['Size'], Any] = np.divide(b,a)

# Print the result
print(c)

a : [1 2 3 4 5]
b : [ 6  7  8  9 10]
[6.         3.5        2.66666667 2.25       2.        ]


## m22 **mode()**

In [80]:

print(f"a : {a}")
print(f"b : {b}")
# Add the two arrays
c : NDArray[Shape['Size'], Any] = np.mod(a,b)

# Print the result
print(c)

a : [1 2 3 4 5]
b : [ 6  7  8  9 10]
[1 2 3 4 5]


## m23 **power()**

In [81]:

print(f"a : {a}")
print(f"b : {b}")
# Add the two arrays
c : NDArray[Shape['Size'], Any] = np.power(b,a)

# Print the result
print(c)

a : [1 2 3 4 5]
b : [ 6  7  8  9 10]
[     6     49    512   6561 100000]


## m24 **max()**

In [84]:

print(f"a : {a}")
print(f"b : {b}")
# Add the two arrays
c : NDArray[Shape['Size'], Any] = np.maximum(b,a)

# Print the result
print(c)

a : [1 2 3 4 5]
b : [ 6  7  8  9 10]
[ 6  7  8  9 10]


## m25 **min()**

In [85]:

print(f"a : {a}")
print(f"b : {b}")
# Add the two arrays
c : NDArray[Shape['Size'], Any] = np.minimum(b,a)

# Print the result
print(c)

a : [1 2 3 4 5]
b : [ 6  7  8  9 10]
[1 2 3 4 5]


## m26 **mean()**

In [90]:

print(f"a : {a}")
print(f"b : {b}")

# Print the result
print(f"mean of b is : {np.mean(b)}")

a : [1 2 3 4 5]
b : [ 6  7  8  9 10]
mean of b is : 8.0


## m27 **median()**

In [94]:

print(f"a : {a}")
# Add the two arrays
c : NDArray[Shape['Size'], Any] = np.median(a)

# Print the result
print(f"mean of a is : {c}")

a : [1 2 3 4 5]
mean of a is : 3.0


# Remaining new methods

In [95]:
import pandas as pd

table_data : pd.DataFrame = pd.read_csv("./explain this _Save and Load Array Data_ and _others_ in table form - explain this _Save and Load Array Data_ and _others_ in table form.csv")

table_data

Method  \
0   Save and Load Array Data   
1                     save()   
2                     load()   
3                  savetxt()   
4                  loadtxt()   
5                     Others   
6                     copy()   
7                     view()   
8                    ravel()   
9                  reshape()   
10                  resize()   
11                 squeeze()   
12                swapaxes()   
13                    take()   
14               transpose()   
15                    sort()   
16                 argsort()   
17                  argmin()   
18                  argmax()   
19            searchsorted()   
20                    clip()   
21                   round()   
22                    ceil()   
23                   floor()   
24                  around()   
25                isfinite()   
26                   isnan()   
27                   isinf()   

                                          Description  \
0                                                 NaN   
1                Save a NumPy array to a binary file.   
2              Load a NumPy array from a binary file.   
3                  Save a NumPy array to a text file.   
4                Load a NumPy array from a text file.   
5                                                 NaN   
6                 Create a new copy of a NumPy array.   
7                 Create a new view of a NumPy array.   
8   Flatten a NumPy array into a one-dimensional a...   
9             Reshape a NumPy array into a new shape.   
10               Resize a NumPy array to a new shape.   
11  Remove any axes of a NumPy array that have onl...   
12                    Swap two axes of a NumPy array.   
13  Extract elements from a NumPy array at given i...   
14                           Transpose a NumPy array.   
15  Sort the elements of a NumPy array in ascendin...   
16  Return the indices of the elements of a NumPy ...   
17  Return the index of the smallest element in a ...   
18  Return the index of the largest element in a N...   
19  Find the indices at which the elements of a Nu...   
20  Limit the elements of a NumPy array to a given...   
21  Round the elements of a NumPy array to a given...   
22  Round the elements of a NumPy array up to the ...   
23  Round the elements of a NumPy array down to th...   
24  Round the elements of a NumPy array to the nea...   
25  Return a NumPy array of booleans indicating wh...   
26  Return a NumPy array of booleans indicating wh...   
27                                                NaN   

                                              Example  
0                                                 NaN  
1                   np.save("my_array.npy", my_array)  
2                  my_array = np.load("my_array.npy")  
3                np.savetxt("my_array.txt", my_array)  
4               my_array = np.loadtxt("my_array.txt")  
5                                                 NaN  
6                   my_array_copy = np.copy(my_array)  
7                   my_array_view = np.view(my_array)  
8             my_array_flattened = np.ravel(my_array)  
9    my_array_reshaped = np.reshape(my_array, (3, 3))  
10                            my_array.resize((3, 3))  
11           my_array_squeezed = np.squeeze(my_array)  
12     my_array_swapped = np.swapaxes(my_array, 0, 1)  
13     my_array_subset = np.take(my_array, [0, 2, 4])  
14       my_array_transposed = np.transpose(my_array)  
15                my_array_sorted = np.sort(my_array)  
16     my_array_sorted_indices = np.argsort(my_array)  
17           my_array_min_index = np.argmin(my_array)  
18           my_array_max_index = np.argmax(my_array)  
19  my_array_search_indices = np.searchsorted(my_a...  
20        my_array_clipped = np.clip(my_array, 0, 10)  
21           my_array_rounded = np.round(my_array, 2)  
22                my_array_ceiled = np.ceil(my_array)  
23              my_array_floored = np.floor(my_array)  
24             my_array_rounded = np.ar